volumes:
  keycloak-postgres:

services:
  postgres:
    image: ${KEYCLOAK_POSTGRES_IMAGE_TAG}
    container_name: postgres
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    networks:
      - keycloak
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${KEYCLOAK_DB_NAME}",
          "-U",
          "${KEYCLOAK_DB_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  keycloak:
    image: ${KEYCLOAK_IMAGE_TAG}
    container_name: keycloak
    volumes:
      - ./deploy/keycloak/http-store:${KEYCLOAK_HTTPS_STORE_DIR_PATH}
      - ./deploy/keycloak/${KEYCLOAK_HTTPS_STORE_TYPE}/certificate:${KEYCLOAK_HTTPS_CERTIFICATE_DIR_PATH}

    environment:
      KEYCLOAK_PRODUCTION: true
      KEYCLOAK_DATABASE_VENDOR: ${KEYCLOAK_DB_TYPE}
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DB_NAME}
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KEYCLOAK_ENABLE_STATISTICS: true

      KEYCLOAK_ENABLE_HTTPS: true
      KEYCLOAK_HTTPS_KEY_STORE_FILE: ${KEYCLOAK_HTTPS_STORE_DIR_PATH}/${KEYCLOAK_HTTPS_KEY_STORE_FILENAME}
      KEYCLOAK_HTTPS_TRUST_STORE_FILE: ${KEYCLOAK_HTTPS_STORE_DIR_PATH}/${KEYCLOAK_HTTPS_TRUST_STORE_FILENAME}
      KEYCLOAK_HTTPS_KEY_STORE_PASSWORD: ${KEYCLOAK_HTTPS_KEY_STORE_PASSWORD}
      KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD: ${KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD}

      KEYCLOAK_HTTPS_USE_PEM: true
      KEYCLOAK_HTTPS_CERTIFICATE_FILE: ${KEYCLOAK_HTTPS_CERTIFICATE_DIR_PATH}/${KEYCLOAK_HTTPS_CERTIFICATE_FILENAME}
      KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: ${KEYCLOAK_HTTPS_CERTIFICATE_DIR_PATH}/${KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILENAME}
    networks:
      - keycloak
    ports:
      - "80:8080"
      - "443:8443"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

networks:
  keycloak:
    driver: bridge
